name = "student-results-backend"
main = "dist/worker.js"
compatibility_date = "2024-09-23" # <-- هذا هو التعديل الصحيح والنهائي
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[[d1_databases]]
binding = "DB"
database_name = "student-results-db"
database_id = "6f6877a4-12d2-4441-b569-abddbd4f3462" # <-- تأكد أن هذا هو الرقم الصحيح الخاص بك